apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: github-listener
  namespace: tekton-pipelines
spec:
  serviceAccountName: tekton-build
  triggers:
    - name: github-push-trigger
      bindings:
        - ref: github-push-trigger-binding 
      template:
        ref: pipeline-trigger-template
  resources:
    kubernetesResource:
      serviceType: ClusterIP